package com.estiuk.studyxp;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.app.usage.UsageStats;import android.app.usage.UsageStatsManager;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity {
    android.content.SharedPreferences p; TextView tvLevel,tvXp,tvStreak,tvTimer,tvReward; ProgressBar progress; Handler h=new Handler(Looper.getMainLooper()); long start=0; boolean running=false; long sessionSeconds=0; int bonusToday=0, penaltyToday=0; String today;
    CheckBox[] checks; final int[] vals={10,15,15,10,15,10,15};
    int[] levels={0,500,1500,3000,5000,8000,12000}; String[] names={"Beginner","Learner","Builder","Problem Solver","Engineer","Advanced","Master"};
    String[] rewards={"—","Small Reward","Medium Reward","Big Reward","Major Reward","Elite Reward","Hair Dryer"};

    @Override public void onCreate(Bundle b){super.onCreate(b); setContentView(R.layout.activity_main); p=getSharedPreferences("studyxp",0); today=date(); migrateDay(); bind(); refresh(); if(hasUsageAccess()) syncUsagePenalty();}
    String date(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    void migrateDay(){today=date(); String saved=p.getString("day",""); if(!today.equals(saved)){p.edit().putString("day",today).putInt("todayFocus",0).putInt("todayBonus",0).putInt("todayPenalty",0).putInt("todayNet",0).putInt("loggedNet",0).putLong("usageBase",0).apply();}}
    void bind(){
        tvLevel=findViewById(R.id.tvLevel);tvXp=findViewById(R.id.tvXp);tvStreak=findViewById(R.id.tvStreak);tvTimer=findViewById(R.id.tvTimer);tvReward=findViewById(R.id.tvReward);progress=findViewById(R.id.progress);
        checks=new CheckBox[]{findViewById(R.id.c1),findViewById(R.id.c2),findViewById(R.id.c3),findViewById(R.id.c4),findViewById(R.id.c5),findViewById(R.id.c6),findViewById(R.id.c7)};
        findViewById(R.id.btnStart).setOnClickListener(v->startSession()); findViewById(R.id.btnStop).setOnClickListener(v->finishSession()); findViewById(R.id.btnAddBonus).setOnClickListener(v->addBonus()); findViewById(R.id.btnPenalty).setOnClickListener(v->manualPenalty()); findViewById(R.id.btnUsage).setOnClickListener(v->usageSetup()); findViewById(R.id.btnHistory).setOnClickListener(v->summary());
    }
    void startSession(){if(running)return; running=true; start=System.currentTimeMillis(); Toast.makeText(this,"Focus started. Stay focused!",Toast.LENGTH_SHORT).show(); tick();}
    void tick(){if(!running)return; sessionSeconds=(System.currentTimeMillis()-start)/1000; tvTimer.setText(fmt(sessionSeconds)); h.postDelayed(this::tick,500);}
    void finishSession(){if(!running)return; running=false; long mins=sessionSeconds/60; if(mins<1){Toast.makeText(this,"Less than 1 minute — no XP added.",Toast.LENGTH_SHORT).show();tvTimer.setText("00:00");return;} int old=p.getInt("todayFocus",0); p.edit().putInt("todayFocus",old+(int)mins).apply(); sessionSeconds=0; tvTimer.setText("00:00"); refresh(); Toast.makeText(this,"+"+mins+" Focus XP",Toast.LENGTH_SHORT).show();}
    String fmt(long s){return String.format(Locale.US,"%02d:%02d",s/60,s%60);}
    void addBonus(){int x=0;for(int i=0;i<checks.length;i++)if(checks[i].isChecked()){x+=vals[i];checks[i].setChecked(false);} if(x==0){Toast.makeText(this,"Select a bonus first.",Toast.LENGTH_SHORT).show();return;} p.edit().putInt("todayBonus",p.getInt("todayBonus",0)+x).apply();refresh();Toast.makeText(this,"+"+x+" Bonus XP",Toast.LENGTH_SHORT).show();}
    void manualPenalty(){ final EditText e=new EditText(this); e.setInputType(2);e.setHint("Minutes"); new AlertDialog.Builder(this).setTitle("Scrolling penalty").setMessage("1 minute = −1 XP").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{try{int m=Integer.parseInt(e.getText().toString()); if(m>0){p.edit().putInt("todayPenalty",p.getInt("todayPenalty",0)+m).apply();refresh();}}catch(Exception ignored){}}).show();}
    boolean hasUsageAccess(){try{UsageStatsManager u=(UsageStatsManager)getSystemService(USAGE_STATS_SERVICE); long t=u.queryUsageStats(UsageStatsManager.INTERVAL_DAILY,System.currentTimeMillis()-1000,System.currentTimeMillis()).size();return t>0;}catch(Exception e){return false;}}
    void usageSetup(){if(!hasUsageAccess()){try{startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS));}catch(Exception e){} Toast.makeText(this,"Allow Usage Access for Study XP, then return and tap this again.",Toast.LENGTH_LONG).show();}else{syncUsagePenalty();}}
    void syncUsagePenalty(){long end=System.currentTimeMillis();Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);long begin=c.getTimeInMillis(); UsageStatsManager u=(UsageStatsManager)getSystemService(USAGE_STATS_SERVICE); List<UsageStats> list=u.queryUsageStats(UsageStatsManager.INTERVAL_DAILY,begin,end); if(list==null)return; String[] pkgs={"com.instagram.android","com.facebook.katana","com.zhiliaoapp.musically"}; long total=0;for(UsageStats s:list){for(String q:pkgs)if(q.equals(s.getPackageName())){total+=s.getTotalTimeInForeground()/60000;break;}} long base=p.getLong("usageBase",0); if(total>base){int delta=(int)(total-base);p.edit().putLong("usageBase",total).putInt("todayPenalty",p.getInt("todayPenalty",0)+delta).apply();refresh(); if(delta>0)Toast.makeText(this,"Auto scrolling/app-usage penalty: −"+delta+" XP",Toast.LENGTH_SHORT).show();}}
    int netToday(){return p.getInt("todayFocus",0)+p.getInt("todayBonus",0)-p.getInt("todayPenalty",0);}
    int totalXp(){return p.getInt("totalXp",0);}
    void refresh(){int net=netToday();int prev=p.getInt("loggedNet",0);if(net!=prev){p.edit().putInt("totalXp",Math.max(0,totalXp()+net-prev)).putInt("loggedNet",net).apply();} int xp=totalXp();int level=0;for(int i=0;i<levels.length;i++)if(xp>=levels[i])level=i;int next=level<levels.length-1?levels[level+1]:levels[level];int base=levels[level];progress.setMax(Math.max(1,next-base));progress.setProgress(Math.max(0,Math.min(next-base,xp-base)));tvLevel.setText("Level "+(level+1)+" — "+names[level]);tvXp.setText("⭐ "+xp+" XP");tvStreak.setText("🔥 "+streak()+" day streak");tvReward.setText("🎁 Next: "+(level<levels.length-1?rewards[level+1]+" at "+next+" XP":"MASTER REWARD UNLOCKED")+"\nToday: "+net+" XP (Focus "+p.getInt("todayFocus",0)+" + Bonus "+p.getInt("todayBonus",0)+" − Penalty "+p.getInt("todayPenalty",0)+")");}
    int streak(){String last=p.getString("lastStudyDay","");String prev=p.getString("prevStudyDay","");int s=p.getInt("streak",0);String d=date();int todayNet=netToday();if(todayNet>=20&&!d.equals(last)){try{Date a=new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(last);Calendar c=Calendar.getInstance();c.setTime(a);c.add(Calendar.DATE,1);String next=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime());s=next.equals(d)?s+1:1;}catch(Exception e){s=1;}p.edit().putString("lastStudyDay",d).putInt("streak",s).apply();}return s;}
    void summary(){refresh();new AlertDialog.Builder(this).setTitle("Today’s Study Log").setMessage("Date: "+today+"\nFocus: "+p.getInt("todayFocus",0)+" min\nBonus: +"+p.getInt("todayBonus",0)+" XP\nPenalty: −"+p.getInt("todayPenalty",0)+" XP\nToday XP: "+netToday()+"\nTotal XP: "+totalXp()+"\nStreak: "+streak()+" days").setPositiveButton("OK",null).show();}
}
